export const events = [
  {
    id: 0,
    title: 'Project Exhibition',
    subtheme: 'AURORA TECH EXPO',
    description: 'A high-octane project showcase and fast-paced tech quiz testing innovation, hardware prototypes, and coding skills.',
    iconType: 'joystick',
    accentColor: '#5de8ef',
    category: 'Past Event',
    date: 'March 18th, 2026',
    time: '10:00 AM Onwards',
    venue: 'Central Labs & Seminar Hall',
    squadLimit: '2-4 member(s)',
    entryFee: '₹60',
    prizePool: '₹2,000/-',
    contacts: 'Drishti Kadam: 8451018435 | Sneha Patil: 7972507907 | Vedant Dhoke: 7387080269'
  },
  {
    id: 1,
    title: 'BGMI',
    subtheme: 'AURORA BGMI',
    description: 'Enter the battleground and prove your squad’s dominance. Strategy, teamwork, and quick decision-making determine survival across 3 intense matches (2 Erangel, 1 Miramar).',
    iconType: 'joystick',
    accentColor: '#fa54bd',
    category: 'Past Event',
    date: 'March 16th, 2026',
    time: '10:00 AM Onwards',
    venue: 'Remote / Lab 402',
    squadLimit: '4 member(s)',
    entryFee: '₹100 / Team',
    prizePool: 'Upto ₹5,000/-',
    contacts: 'Rohit Zore: 8879466037 | Sarthak Gavas: 9152589769'
  },
  {
    id: 2,
    title: 'Escape Room',
    subtheme: 'AURORA ESCAPE ROOM',
    description: 'Crack codes and unlock secrets to escape before time runs out. Logical thinking and puzzle-solving are the keys to breaking out.',
    iconType: 'ghost',
    accentColor: '#5de8ef',
    category: 'Past Event',
    date: 'March 17th, 2026',
    time: '10:00 AM Onwards',
    venue: 'Mystery Arena',
    squadLimit: '2-4 member(s)',
    entryFee: '₹100 / Team',
    prizePool: 'Upto ₹5,000/-',
    contacts: 'Maitreya Channa: 8108210981 | Kshama Nayak: 9773210137'
  },
  {
    id: 3,
    title: 'Talent Show',
    subtheme: 'AURORA TALENT SHOW',
    description: 'A stage for creativity and expression. Show your talent through singing, dancing, comedy, or unique live performances.',
    iconType: 'pacman',
    accentColor: '#f5db64',
    category: 'Past Event',
    date: 'March 18th, 2026',
    time: '2:00 PM Onwards',
    venue: 'Main Stage / Auditorium',
    squadLimit: '1-2 member(s)',
    entryFee: '₹50 - Solo | ₹80 - Duet',
    prizePool: '₹1,500/-',
    contacts: 'Rishi Yadav: 9328510397 | Omkar Shingote: 9594231594 | Urvi Turbhekar: 7738612080'
  },
  {
    id: 4,
    title: 'Human Ludo',
    subtheme: 'AURORA HUMAN LUDO',
    description: 'A life-size version of the classic board game. Players themselves become the tokens on the giant interactive board.',
    iconType: 'coin',
    accentColor: '#f5db64',
    category: 'Past Event',
    date: 'March 16th - 18th, 2026',
    time: 'Full Day Event',
    venue: 'College Podium',
    squadLimit: '4 member(s)',
    entryFee: '₹100 / Team',
    prizePool: '₹3,000/-',
    contacts: 'Bhoomi Naik: 8452831249 | Gayatri Chavan: 8355873028'
  },
  {
    id: 5,
    title: 'Pegasus',
    subtheme: 'AURORA PEGASUS',
    description: 'The flagship inter-collegiate technical event where innovative engineering prototypes and software solutions take flight.',
    iconType: 'joystick',
    accentColor: '#5de8ef',
    category: 'Past Event',
    date: 'March 16th - 18th, 2026',
    time: '10:00 AM Onwards',
    venue: 'Main Quadrangle & Labs',
    squadLimit: '2-4 member(s)',
    entryFee: '₹100 / Team',
    prizePool: 'Upto ₹7,000/-',
    contacts: 'AISAC Technical Committee'
  },
  {
    id: 6,
    title: "Teacher's Day",
    subtheme: 'PAC-MAN THEME SPECIAL',
    description: 'A special tribute to our real high-score holders: our teachers! Chase clues, dodge ghosts, power up with knowledge, and celebrate our educators with arcade fun.',
    iconType: 'pacman',
    accentColor: '#f5db64',
    category: 'Pac-Man Event',
    date: '5th September',
    time: '11:00 AM Onwards',
    venue: 'Seminar Hall & Student Lounge',
    squadLimit: 'Open to All',
    entryFee: 'Free Entry',
    prizePool: 'Faculty Trophies & Rewards',
    contacts: 'AISAC Executive Council'
  },
  {
    id: 7,
    title: 'FE Orientation',
    subtheme: 'CONTINUOUS LIVE EVENT',
    description: 'Welcoming First-Year Engineering students into the world of AI, tech innovation, coding workshops, and campus community leadership.',
    iconType: 'coin',
    accentColor: '#5de8ef',
    category: 'Live Event',
    date: 'October 2026',
    time: '10:00 AM - 4:00 PM',
    venue: 'Main Auditorium & AI Hub',
    squadLimit: 'FE Students',
    entryFee: 'Open Access',
    prizePool: 'Starter Kits & Certificates',
    contacts: 'AISAC Student Mentors'
  }
];
