export const heads = [
  { id: 'h-1', name: 'Aayush Karbhal', role: 'Chairman', dept: 'AISAC & CSI', year: '3rd Year', avatarColor: 'linear-gradient(135deg, #f667c5, #85e3ed)', initials: 'AK' },
  { id: 'h-2', name: 'Aditi Sahu', role: 'President', dept: 'ISTE', year: '3rd Year', avatarColor: 'linear-gradient(135deg, #85e3ed, #f667c5)', initials: 'AS' },
  { id: 'h-3', name: 'Aarya Yerankar', role: 'Secretary', dept: 'AISAC & CSI', year: '3rd Year', photo: '/assets/aarya-yerankar.png', photoPos: 'center top', photoTransform: 'translateY(-16px) scale(1.12)', avatarColor: 'linear-gradient(135deg, #d4f77c, #f667c5)', initials: 'AY' },
  { id: 'h-4', name: 'Aadi Kundar', role: 'Secretary', dept: 'ISTE', year: '3rd Year', avatarColor: 'linear-gradient(135deg, #f5db64, #5de8ef)', initials: 'AK' },
  { id: 'h-5', name: 'Trisha Shetty', role: 'Joint Secretary', dept: 'AISAC & CSI', year: '3rd Year', photo: '/assets/trisha-shetty.jpg', photoPos: 'center top', avatarColor: 'linear-gradient(135deg, #85e3ed, #d4f77c)', initials: 'TS' },
  { id: 'h-6', name: 'Aditya Chaurasia', role: 'Joint Secretary', dept: 'ISTE', year: '3rd Year', avatarColor: 'linear-gradient(135deg, #fa54bd, #85e3ed)', initials: 'AC' },
  { id: 'h-7', name: 'Darpan Shah', role: 'Treasurer', dept: 'AISAC & CSI', year: '3rd Year', photo: '/assets/darpan-shah.jpg', photoPos: 'center top', avatarColor: 'linear-gradient(135deg, #f667c5, #141513)', initials: 'DS' },
  { id: 'h-8', name: 'Hiya Modi', role: 'Treasurer', dept: 'ISTE', year: '3rd Year', avatarColor: 'linear-gradient(135deg, #5de8ef, #f5db64)', initials: 'HM' },
  { id: 'h-9', name: 'Parth Kariya', role: 'Technical Head', dept: 'AISAC & CSI', year: '3rd Year', avatarColor: 'linear-gradient(135deg, #85e3ed, #141513)', initials: 'PK' },
  { id: 'h-10', name: 'Ayush Meshram', role: 'Technical Head', dept: 'ISTE', year: '3rd Year', photo: '/assets/ayush-meshram.jpg', photoPos: 'center 12%', photoTransform: 'scale(1.48) translateY(2px)', avatarColor: 'linear-gradient(135deg, #f667c5, #85e3ed)', initials: 'AM' },
  { id: 'h-11', name: 'Pankaj Gujuri', role: 'Documentation Head', dept: 'AISAC & CSI', year: '3rd Year', avatarColor: 'linear-gradient(135deg, #d4f77c, #141513)', initials: 'PG' },
  { id: 'h-12', name: 'Anuj Gangawane', role: 'Documentation Head', dept: 'ISTE', year: '3rd Year', avatarColor: 'linear-gradient(135deg, #85e3ed, #fa54bd)', initials: 'AG' },
  { id: 'h-13', name: 'Sharayou Sanap', role: 'PRO Head', dept: 'AISAC & CSI', year: '3rd Year', photo: '/assets/sharyou-sanap.png', photoPos: 'center top', avatarColor: 'linear-gradient(135deg, #f667c5, #d4f77c)', initials: 'SS' },
  { id: 'h-14', name: 'Archit Shinde', role: 'Infra and Security Head', dept: 'AISAC & CSI', year: '3rd Year', photo: '/assets/archit-shinde.jpg', photoPos: 'center top', avatarColor: 'linear-gradient(135deg, #85e3ed, #d4f77c)', initials: 'AS' }
];

export const members = [
  { id: 'm-1', name: 'Atharv Patil', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #f667c5, #85e3ed)', initials: 'AP' },
  { id: 'm-2', name: 'Jiya Sawant', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #d4f77c, #f667c5)', initials: 'JS' },
  { id: 'm-3', name: 'Vishwesh Deshmukh', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #85e3ed, #d4f77c)', initials: 'VD' },
  { id: 'm-4', name: 'Jai Rajput', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #f5db64, #5de8ef)', initials: 'JR' },
  { id: 'm-5', name: 'Samruddhi Mahadik', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #fa54bd, #85e3ed)', initials: 'SM' },
  { id: 'm-6', name: 'Vedika Koli', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #5de8ef, #f5db64)', initials: 'VK' },
  { id: 'm-7', name: 'Sushmita Gowda', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #d4f77c, #85e3ed)', initials: 'SG' },
  { id: 'm-8', name: 'Attadeep Ingle', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #f667c5, #d4f77c)', initials: 'AI' },
  { id: 'm-9', name: 'Purva Pokharkar', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #85e3ed, #141513)', initials: 'PP' },
  { id: 'm-10', name: 'Kunal Raut', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #f5db64, #fa54bd)', initials: 'KR' },
  { id: 'm-11', name: 'Shruti Nilesh Jadhav', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #d4f77c, #f667c5)', initials: 'SJ' },
  { id: 'm-12', name: 'Shruti U Jadhav', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #85e3ed, #d4f77c)', initials: 'SJ' },
  { id: 'm-13', name: 'Himani Koli', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #fa54bd, #5de8ef)', initials: 'HK' },
  { id: 'm-14', name: 'Amruta Kale', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #f667c5, #85e3ed)', initials: 'AK' },
  { id: 'm-15', name: 'Aayushi More', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #d4f77c, #f5db64)', initials: 'AM' },
  { id: 'm-16', name: 'Sanika Kathore', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #85e3ed, #f667c5)', initials: 'SK' },
  { id: 'm-17', name: 'Dhiraj Balotia', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #5de8ef, #d4f77c)', initials: 'DB' },
  { id: 'm-18', name: 'Harish Choudhary', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #f667c5, #141513)', initials: 'HC' },
  { id: 'm-19', name: 'Shaswat Prasad', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #d4f77c, #85e3ed)', initials: 'SP' },
  { id: 'm-20', name: 'Durva Bhosle', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #fa54bd, #f5db64)', initials: 'DB' },
  { id: 'm-21', name: 'Sakshi Bajbalkar', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #85e3ed, #f667c5)', initials: 'SB' },
  { id: 'm-22', name: 'Harshini Vuradi', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #f5db64, #d4f77c)', initials: 'HV' },
  { id: 'm-23', name: 'Akhilesh Shitole', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #5de8ef, #fa54bd)', initials: 'AS' },
  { id: 'm-24', name: 'Varshani Chinthakinda', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #f667c5, #d4f77c)', initials: 'VC' },
  { id: 'm-25', name: 'Dolly Nimje', role: 'Committee Member', year: '2nd Year', avatarColor: 'linear-gradient(135deg, #85e3ed, #141513)', initials: 'DN' }
];
